services:
  db:
    image: postgres
    container_name: job_dispatcher_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  app:
    build: .  # Uses the Dockerfile
    container_name: job_dispatcher_app
    depends_on:
      - db
    ports:
      - "8080:8080"  # Map host port 8080 → container port 8080
    environment:
      POSTGRES_HOST: db  # Critical: Use service name, not localhost!
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: job_dispatcher
      POSTGRES_PORT: 5432
    volumes:
      - .:/app  # Optional: Sync local code for live reloads (dev only)

volumes:
  pg_data:
